spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Dt3p8SFTj
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

aws.region=${AWS_REGION:us-east-1}

aws.s3.profile-images-bucket=${PROFILE_IMAGES_BUCKET:wevolunteer-files-images-110441303427}
aws.s3.upload-url-duration=${PROFILE_IMAGE_UPLOAD_URL_DURATION:15m}
aws.s3.download-url-duration=${PROFILE_IMAGE_DOWNLOAD_URL_DURATION:60m}

aws.sns.topic-arn=${SNS_TOPIC_ARN:arn:aws:sns:us-east-1:110441303427:wevolunteer-notifications}