package com.wevolunteer.backend.dto;

import jakarta.validation.constraints.NotBlank;

/**
 * Asks for a short-lived URL that uploads one opportunity image directly to S3.
 *
 * <p>Only the content type is accepted. The object key — extension, unique file name, and the
 * organization prefix — is generated by the backend, so a client cannot choose where its upload
 * lands.
 */
public record OpportunityImageUploadUrlRequest(
        @NotBlank String contentType
) {}
