package com.wevolunteer.backend.dto;

import jakarta.validation.constraints.NotBlank;

/**
 * Asks for a short-lived URL that uploads one profile image directly to S3.
 *
 * <p>Only the content type is accepted. The object key — extension, unique file name, and the
 * owner prefix — is generated by the backend from the access token.
 */
public record ProfileImageUploadUrlRequest(
        @NotBlank String contentType
) {}
